apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
          livenessProbe:
            # rota para testar o container
            httpGet:
              path: /
              port: 80
            # periodo em segundos para testar
            periodSeconds: 10
            # max de falhas toleradas antes de reiniciar o container
            failureThreshold: 3
            # trava inicial antes do começar a testar o container
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            # se ele não conseguir executar falar em X na proxima ele envia as requisições para o container
            failureThreshold: 5
            initialDelaySeconds: 3 
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias