apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sessao-pvc
spec:
  # define o tipo de acesso
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # define o tamanho do disco
      storage: 1Gi