apiVersion: v1
kind: Pod
metadata:
  name: pod-pv
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-pv
  volumes:
    - name: primeiro-pv
      # definindo qual é o volume que iremos persistir
      persistentVolumeClaim:
        # definido pelo arquivo pvc.yml
        claimName: pvc-1