apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP # ClusterIP não comunica externamente;
  selector:
    app: segundo-pod
  ports:
    - port: 9000
      targetPort: 80
